// <auto-generated />
namespace NBP_app.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class audit_all : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(audit_all));
        
        string IMigrationMetadata.Id
        {
            get { return "202205102041372_audit_all"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
